In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Exercise 1: Create two 1D arrays of length 5 with your choice of integers

In [2]:
arr1=np.array([2,4,6,8,10])
arr2=np.array([5,10,15,20,25])

In [3]:
# Compute their element-wise product and print the result.

arr_pdct=arr1*arr2
arr_pdct

array([ 10,  40,  90, 160, 250])

### Exercise 2: Shaping and reshaping arrays

In [4]:
a1=np.arange(12)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a1_reshaped=a1.reshape(3,4)
a1_reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a2=np.arange(16)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
a_res=a2.reshape(4,4)
a_res

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 3: Indexing and slicing

In [9]:
mtx = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Matrix:', mtx)

Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]

In [11]:
mtx[2:]

array([[7, 8, 9]])

In [12]:
mtx[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
mtx[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
mtx[1,1]

np.int64(5)

In [17]:
# Create a 3x3 matrix with values from 10 to 18 (use np.arange() and reshape)

mtx = np.arange(10,19)
mtx

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [18]:
mtx1=mtx.reshape(3,3)
mtx1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
# Extract and print the first column and the element at position (1,2)

mtx1[:,1]

array([11, 14, 17])

In [21]:
mtx1[1,2]

np.int64(15)

In [26]:
# Exercise 4: Create an array with values [2, 4, 6, 8, 10]

arr2= np.array([2,4,6,8,10])
arr2

array([ 2,  4,  6,  8, 10])

In [28]:
# Compute and print its element-wise square, standard deviation, and sum
sqr = arr2**2
sd = np.mean(arr2)
sqr

array([  4,  16,  36,  64, 100])

In [29]:
sd

np.float64(6.0)

In [31]:
df=pd.read_csv('housing-5.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [34]:
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [35]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [36]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
longitude,20640.0,-119.569704,2.003532,-124.3500,-121.8000,-118.4900,-118.01000,-114.3100
latitude,20640.0,35.631861,2.135952,32.5400,33.9300,34.2600,37.71000,41.9500
housing_median_age,20640.0,28.639486,12.585558,1.0000,18.0000,29.0000,37.00000,52.0000
total_rooms,20640.0,2635.763081,2181.615252,2.0000,1447.7500,2127.0000,3148.00000,39320.0000
total_bedrooms,20433.0,537.870553,421.385070,1.0000,296.0000,435.0000,647.00000,6445.0000
population,20640.0,1425.476744,1132.462122,3.0000,787.0000,1166.0000,1725.00000,35682.0000
households,20640.0,499.539680,382.329753,1.0000,280.0000,409.0000,605.00000,6082.0000
median_income,20640.0,3.870671,1.899822,0.4999,2.5634,3.5348,4.74325,15.0001
median_house_value,20640.0,206855.816909,115395.615874,14999.0000,119600.0000,179700.0000,264725.00000,500001.0000

In [37]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [38]:
df['total_bedrooms']

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [39]:
can=['population', 'households']
df[can]

       population  households
0           322.0       126.0
1          2401.0      1138.0
2           496.0       177.0
3           558.0       219.0
4           565.0       259.0
...           ...         ...
20635       845.0       330.0
20636       356.0       114.0
20637      1007.0       433.0
20638       741.0       349.0
20639      1387.0       530.0

[20640 rows x 2 columns]

In [40]:
df[['population', 'households']]

       population  households
0           322.0       126.0
1          2401.0      1138.0
2           496.0       177.0
3           558.0       219.0
4           565.0       259.0
...           ...         ...
20635       845.0       330.0
20636       356.0       114.0
20637      1007.0       433.0
20638       741.0       349.0
20639      1387.0       530.0

[20640 rows x 2 columns]

In [41]:
df[['median_income','median_house_value']]

       median_income  median_house_value
0             8.3252            452600.0
1             8.3014            358500.0
2             7.2574            352100.0
3             5.6431            341300.0
4             3.8462            342200.0
...              ...                 ...
20635         1.5603             78100.0
20636         2.5568             77100.0
20637         1.7000             92300.0
20638         1.8672             84700.0
20639         2.3886             89400.0

[20640 rows x 2 columns]

In [43]:
# creating a new column

df['population_20']=df['population']*3
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,population_20
0,-122.23,37.88,41.0,880.0,129.0,966.0,126.0,8.3252,452600.0,NEAR BAY,2898.0
1,-122.22,37.86,21.0,7099.0,1106.0,7203.0,1138.0,8.3014,358500.0,NEAR BAY,21609.0
2,-122.24,37.85,52.0,1467.0,190.0,1488.0,177.0,7.2574,352100.0,NEAR BAY,4464.0
3,-122.25,37.85,52.0,1274.0,235.0,1674.0,219.0,5.6431,341300.0,NEAR BAY,5022.0
4,-122.25,37.85,52.0,1627.0,280.0,1695.0,259.0,3.8462,342200.0,NEAR BAY,5085.0
...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,2535.0,330.0,1.5603,78100.0,INLAND,7605.0
20636,-121.21,39.49,18.0,697.0,150.0,1068.0,114.0,2.5568,77100.0,INLAND,3204.0
20637,-121.22,39.43,17.0,2254.0,485.0,3021.0,433.0,1.7000,92300.0,INLAND,9063.0
20638,-121.32,39.43,18.0,1860.0,409.0,2223.0,349.0,1.8672,84700.0,INLAND,6669.0
20639,-121.24,39.37,16.0,2785.0,616.0,4161.0,530.0,2.3886,89400.0,INLAND,12483.0

In [48]:
df['households']=np.round(df['households']*3, 3)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,population_20
0,-122.23,37.88,41.0,880.0,129.0,966.0,1134.0,8.3252,452600.0,NEAR BAY,2898.0
1,-122.22,37.86,21.0,7099.0,1106.0,7203.0,10242.0,8.3014,358500.0,NEAR BAY,21609.0
2,-122.24,37.85,52.0,1467.0,190.0,1488.0,1593.0,7.2574,352100.0,NEAR BAY,4464.0
3,-122.25,37.85,52.0,1274.0,235.0,1674.0,1971.0,5.6431,341300.0,NEAR BAY,5022.0
4,-122.25,37.85,52.0,1627.0,280.0,1695.0,2331.0,3.8462,342200.0,NEAR BAY,5085.0
...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,2535.0,2970.0,1.5603,78100.0,INLAND,7605.0
20636,-121.21,39.49,18.0,697.0,150.0,1068.0,1026.0,2.5568,77100.0,INLAND,3204.0
20637,-121.22,39.43,17.0,2254.0,485.0,3021.0,3897.0,1.7000,92300.0,INLAND,9063.0
20638,-121.32,39.43,18.0,1860.0,409.0,2223.0,3141.0,1.8672,84700.0,INLAND,6669.0
20639,-121.24,39.37,16.0,2785.0,616.0,4161.0,4770.0,2.3886,89400.0,INLAND,12483.0

In [49]:
# remove columns

df.drop(['population_20'], axis=1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,966.0,1134.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,7203.0,10242.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,1488.0,1593.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,1674.0,1971.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,1695.0,2331.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,2535.0,2970.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,1068.0,1026.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,3021.0,3897.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,2223.0,3141.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,4161.0,4770.0,2.3886,89400.0,INLAND

Age of students in a Master program:
22, 21, 23, 28, 23, 34, 30, 24, 49, 27, 23, 22, 32, 28, 26

Write a simple Python program (Jupyter Notebook) to calculate the following.

Mean, Median, Mode, Range, Min, Max

In [52]:
import statistics as st

In [51]:
data = [22, 21, 23, 28, 23, 34, 30, 24, 49, 27, 23, 22, 32, 28, 26]

In [54]:
# Calculating the mean
data_mean=st.mean(data)
data_mean

27.466666666666665

In [55]:
# Calculate the mode
data_mode=st.mode(data)
data_mode

23

In [56]:
# Calculate the median
data_median=st.median(data)
data_median

26

In [65]:
# Calculating the maximum and minimum values

min_=min(data)
max_=max(data)
print('The maximum value is:', max_, 'and the minimum value is:', min_)
print('The range is', min_,',',max_)
print(min_, max_)

The maximum value is: 49 and the minimum value is: 21
The range is 21 , 49
21 49

Write a simple Python program (Jupyter Notebook), to find the
interquartile range of the data

22, 21, 23, 28, 23, 34, 30, 24, 49, 27, 23, 22, 32, 28, 26

In [66]:
data

[22, 21, 23, 28, 23, 34, 30, 24, 49, 27, 23, 22, 32, 28, 26]

In [67]:
range1=max_-min_
range1

28

In [69]:
# Finding the 25th percentile
# sort data first in ascending order using the function sorted()
sort_data=sorted(data)
data_25=len(sort_data)*0.25
data_25

3.75

In [71]:
# Finding the 75th percentile
data_75=len(sort_data)*0.75
data_75

11.25

In [73]:
# IQR means subtract the 25th from the 75th. Number needs to be rounded

IQR = data_75-data_25
int(IQR)

7

In [89]:
import statistics as st
import numpy as np

array=[]

for _ in range(15):
    no=int(input('Input number:' ))
    array.append(no)
    a=np.array(array)

# Calculate the mean
a_mean = st.mean(a)

#Calculate the median
a_median=st.median(a)

#Calculate Mode
a_mode=st.mode(a)

# Maximum and Minimum values
a_min=min(a)
a_max=max(a)

#Calculate Range
a_range=max(a)-min(a)

# Finding the interquartile range
# Calculate the 25th percentile
a_sorted=sorted(a)
a_25=len(a_sorted)*0.25

# Calculate the 75th percentile
a_75=len(a_sorted)*0.75

# IQR
IQR=a_75-a_25

# 22, 21, 23, 28, 23, 34, 30, 24, 49, 27, 23, 22, 32, 28, 26
print('Array:', a)
print('Mean:',a_mean)
print('Median:', a_median)
print('Mode:', a_mode)
print('The range is between', a_min, 'and', a_max, 'which is', a_range)
print('The 25th percentile:', a_25)
print('The 75th percentile:', a_75)
print('Your IQR:', IQR)

Input number: 22
Input number: 21
Input number: 23
Input number: 28
Input number: 23
Input number: 34
Input number: 30
Input number: 24
Input number: 49
Input number: 27
Input number: 23
Input number: 22
Input number: 32
Input number: 28
Input number: 26

Array: [22 21 23 28 23 34 30 24 49 27 23 22 32 28 26]
Mean: 27
Median: 26
Mode: 23
The range is between 21 and 49 which is 28
The 25th percentile: 3.75
The 75th percentile: 11.25
Your IQR: 7.5